//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_ShoppipngCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string ProductID { get; set; }
        public string Name { get; set; }
        public decimal Quantity { get; set; }
        public decimal Total { get; set; }

        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string CategoryID { get; set; }
        public string ImageFile { get; set; }
        public decimal UnitPrice { get; set; }
    }
}
